# Getting Started

## 1.Tensors
### Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

### 1.1 Construct a 5x3 matrix, uninitialized:

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38]])


### 1.2 Construct a randomly initialized matrix:

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1027, 0.4515, 0.0047],
        [0.8438, 0.3453, 0.2697],
        [0.2071, 0.9694, 0.8702],
        [0.6206, 0.4489, 0.5478],
        [0.8613, 0.7704, 0.1056]])


### 1.3 Construct a matrix filled zeros and of dtype long:

In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### 1.4 Construct a tensor directly from data:

In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


### 1.5 Or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [9]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8079, -0.4784, -1.2436],
        [-0.7329, -0.2039, -0.0319],
        [ 0.0119, -0.4188, -0.0916],
        [-0.1683, -1.1340,  0.7934],
        [ 0.9762,  0.7146, -0.4861]])


### 1.6 Get its size:

In [10]:
print(x.size())             #torch.Size is in fact a tuple, so it supports all tuple operations.

torch.Size([5, 3])


# 2.Addition
### 2.1 Syntax 1

In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.6370, -0.2607, -1.0688],
        [-0.2614,  0.3291,  0.2949],
        [ 0.5626, -0.1893,  0.8746],
        [-0.1670, -0.4518,  1.4602],
        [ 1.8115,  1.1468, -0.0329]])


### 2.2 Syntax 2

In [12]:
print(torch.add(x, y))

tensor([[ 1.6370, -0.2607, -1.0688],
        [-0.2614,  0.3291,  0.2949],
        [ 0.5626, -0.1893,  0.8746],
        [-0.1670, -0.4518,  1.4602],
        [ 1.8115,  1.1468, -0.0329]])


### 2.3 Providing an output tensor as argument

In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.6370, -0.2607, -1.0688],
        [-0.2614,  0.3291,  0.2949],
        [ 0.5626, -0.1893,  0.8746],
        [-0.1670, -0.4518,  1.4602],
        [ 1.8115,  1.1468, -0.0329]])


### 2.4  In-place addition

In [14]:
# adds x to y : Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.
y.add_(x)
print(y)

tensor([[ 1.6370, -0.2607, -1.0688],
        [-0.2614,  0.3291,  0.2949],
        [ 0.5626, -0.1893,  0.8746],
        [-0.1670, -0.4518,  1.4602],
        [ 1.8115,  1.1468, -0.0329]])


### 2.5 You can use standard NumPy-like indexing with all bells and whistles!

In [15]:
print(x[:, 1])

tensor([-0.4784, -0.2039, -0.4188, -1.1340,  0.7146])


### 2.6 Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### 2.7 If you have a one element tensor, use .item() to get the value as a Python number

In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4260])
0.4259827733039856


# 3.NumPy Bridge
### Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

### The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

## 3.1 Converting a Torch Tensor to a NumPy Array

In [18]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


### See how the numpy array changed in value.

In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## 3.2 Converting NumPy Array to Torch Tensor
### See how changing the np array changed the Torch Tensor automatically

In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# 4.CUDA Tensors
### Tensors can be moved onto any device using the .to method.

In [24]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.4260], device='cuda:0')
tensor([1.4260], dtype=torch.float64)
